#190  Notificar usuario
BotGaia/Gaia pull request #16
Opened 2019-05-20 20:11 UTC by Ed-vL

Nesse pull request foi feito:
Issue #190
Historia #23
Fluxo para requisitar notificação ao sistema

2019-05-21 01:59 UTC, CalebeRios requested changes

2019-05-21 01:59 UTC, CalebeRios commented on bot/actions/action_user.py
> +
Linha desnecessária

2019-05-21 01:59 UTC, CalebeRios commented on bot/actions/action_user.py
Linha desnecessária

2019-05-21 02:07 UTC, CalebeRios approved these changes

2019-05-21 03:01 UTC, AmandaMuniz requested changes
Olá, um pr foi aceito antes do seu. Atualize com a dev, por favor

2019-05-29 03:40 UTC, CalebeRios approved these changes

2019-05-29 03:40 UTC, CalebeRios commented on bot/actions/environment.py
> +
Linha desnecessária

2019-05-29 03:40 UTC, CalebeRios commented on bot/actions/environment.py
> +        URL = 'https://esporte.hml.ga'
E a url está errada, o correto é esporte.botgaia.ga.

Adicionar o `production` que vai ser esporte.botgaia.ga

2019-05-29 03:40 UTC, CalebeRios commented on bot/actions/utils.py
> +
linha desnecessária

2019-05-29 03:40 UTC, CalebeRios commented on bot/actions/utils.py
> +
Linha desnecessária

2019-05-29 03:40 UTC, CalebeRios commented on bot/data/stories/stories.md
> +## Generated Story 3611785792353468681
Retirar esse número gigante

2019-05-29 03:41 UTC, CalebeRios requested changes
Alterar os comentários feitos

2019-05-29 14:25 UTC, Ed-vL commented on bot/actions/environment.py
> +
O flake8 pede duas linhas vazias antes de toda função, já deixei assim para facilitar o merge

2019-05-30 00:48 UTC, CalebeRios commented on bot/actions/environment.py
> +
Eita, não sabia kk

2019-05-30 00:51 UTC, CalebeRios approved these changes

2019-05-30 01:01 UTC, AmandaMuniz approved these changes

2019-05-30 01:01 UTC, merged