Fix #210 melhorar fluxo
BotGaia/Gaia pull request #18
Opened 2019-05-25 03:56 UTC by LhTaira

Nesse pull request foi feito:

Issue #210
Melhora de fluxo de conversa da Gaia
Alteração do fludo da gaia para focar mais em esporte
Correção de erros da folha de estilo

2019-05-25 04:00 UTC, CalebeRios commented
Descomentem o que esta comentado do flake8 no gitlab ci @Ed-vL @LhTaira

2019-05-25 15:31 UTC, CalebeRios requested changes
Está quebrando após eu selecionar o local na lista. Verificar isso.

2019-05-25 15:31 UTC, CalebeRios commented on bot/actions/action_local.py
> +        URL = 'https://local.hml.botgaia.ga/listLocales'
E cadê o endpoint diferente dependendo do ambiente?

2019-05-25 15:31 UTC, CalebeRios commented on bot/actions/action_local.py
> +            data_message_2 = 'poderia informar qual o número '
Tem poderia repetido aqui

2019-05-25 15:31 UTC, CalebeRios commented on bot/actions/action_user.py
> +        URL = "http://68.183.43.29:30000//createNotification"
Não é essa rota a correta, por favor alterar

2019-05-25 15:31 UTC, CalebeRios commented on bot/test_stories.py
> +
O flake8 pede essas duas linhas?

2019-05-25 15:31 UTC, CalebeRios commented on bot/domain.yml
> +  - text: "Você pode me pedir:\n\n- Melhores esportes para seu clima\n- Recomendação de um\
`Recomendação de umesporte` corrigir isso pfvr

2019-05-29 00:46 UTC, LhTaira commented on bot/test_stories.py
> +
Sim. Ele sempre pede na separação de funções.

2019-05-29 00:49 UTC, LhTaira commented on bot/domain.yml
> +  - text: "Você pode me pedir:\n\n- Melhores esportes para seu clima\n- Recomendação de um\
Tem um espaço na linha 172 antes de "esporte".

2019-05-29 02:35 UTC, Ed-vL commented on bot/actions/action_local.py
> +        URL = 'https://local.hml.botgaia.ga/listLocales'
Isso eu fiz no outro PR que está aberto

2019-05-30 01:08 UTC, AmandaMuniz requested changes
Atualizar com a dev

2019-05-30 03:01 UTC, CalebeRios approved these changes

2019-05-30 16:19 UTC, AmandaMuniz approved these changes

2019-05-30 16:19 UTC, merged