Fix #233 US28 manter ciclone
BotGaia/Gaia pull request #26
Opened 2019-06-06 04:11 UTC by micaellagouveia

Nesse pull request foi feito:
Issue #233
História US28
Criação do fluxo e actions do Gaia-Ciclone

2019-06-06 10:49 UTC, CalebeRios requested changes

2019-06-06 10:49 UTC, CalebeRios commented on bot/actions/environment.py
> +        URL = 'https://cyclone.hml.botgaia.ga'
Não é `cyclone` e sim `ciclone`, eu utilizei da palavra no português

2019-06-06 10:49 UTC, CalebeRios commented on bot/actions/environment.py
> +        URL = 'https://cyclone.botgaia.ga'
Mesma coisa aqui

2019-06-06 12:22 UTC, CalebeRios approved these changes

2019-06-06 23:27 UTC, CalebeRios requested changes
Comentários sobre o fluxo dos serviços

2019-06-06 23:27 UTC, CalebeRios commented on bot/actions/environment.py
> +        URL = 'https://ciclone.hml.botgaia.ga'
Como conversado em daily, substitua essas rotas passando pelo gateway

2019-06-07 21:13 UTC, CalebeRios approved these changes
Ok!

2019-06-07 21:57 UTC, AmandaMuniz approved these changes

2019-06-07 21:58 UTC, merged