#201 US25 - Eu como usuário desejo que o Gateway autentique minhas requisições
BotGaia/Gaia pull request #27
Opened 2019-06-06 23:31 UTC by SamButers

Nesse pull request foi feito:

Issue #201
User Story #25
Modificação das rotas e parâmetros de requisição em Gaia

2019-06-06 23:34 UTC, CalebeRios requested changes

2019-06-06 23:34 UTC, CalebeRios commented on bot/actions/action_local.py
> +        response = requests.get(URL+'/', params=payload)
Já que todos vão utilizar o `/`, coloca o barra dentro da URL logo, que fica no configGateway. Assim não precisa fazer essa concaternação

2019-06-07 20:24 UTC, CalebeRios approved these changes

2019-06-07 21:55 UTC, AmandaMuniz approved these changes

2019-06-07 21:55 UTC, merged